# Default values for spaceone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
installedBy:
  author: jinsu

namePrefix: "{{ .Realease.Name }}"
namespace: default
gracePeriod: 3

mongo:
  enabled: true
  initialize: true
  image: mongo
  replicas: 1
  imagePullPolicy: IfNotPresent
  username: mongouser
  password: mongopassword
  host: mongo
  port: 27017
  service:
    type: ClusterIP
    annotations:
      nil: nil
    nodePort:

redis:
  enabled: true
  image: redis
  imagePullPolicy: IfNotPresent
  host: redis
  port: 6379
  service:
    type: ClusterIP
    annotations:
      nil: nil
    nodePort:

consul:
  enabled: true
  image: consul:1.7.3
  imagePullPolicy: IfNotPresent
  host: consul
  service:
    type: ClusterIP
    annotations:
      nil: nil
    nodePort:

backend:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 3
  labels:
  imagePullPolicy: IfNotPresent

  services:
    config:
      enabled: true
      image: spaceone/config:latest
      endpoint: config:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    identity:
      enabled: true
      image: spaceone/identity:latest
      endpoint: identity:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    inventory:
      enabled: true
      image: spaceone/inventory:latest
      endpoint: inventory:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    inventoryWorker:
      enabled: true
      image: spaceone/inventory:latest
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    inventoryScheduler:
      enabled: true
      image: spaceone/inventory:latest
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    monitoring:
      enabled: true
      image: spaceone/monitoring:latest
      endpoint: monitoring:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    plugin:
      enabled: true
      image: spaceone/plugin:latest
      endpoint: plugin:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    repository:
      enabled: true
      image: spaceone/repository:latest
      endpoint: repository:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    secret:
      enabled: true
      image: spaceone/secret:latest
      endpoint: secret:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:
      awsSecretManagerConnector:
        awsAccessKeyId:
        awsSecretAccessKey:
        regionName: ap-northeast-2

    statistics:
      enabled: true
      image: spaceone/statistics:latest
      endpoint: statistics:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:

    statisticsScheduler:
      enabled: true
      image: spaceone/statistics:latest
      service:
        type: ClusterIP
        annotations:
          nil: nil
        nodePort:


frontend:
#  domain: root # 안먹힘
  enabled: true
  replicas: 1
  imagePullPolicy: IfNotPresent
  console:
    enabled: true
    endpoint: console-client
    image: spaceone/console:latest
    host: console
    service:
      type: ClusterIP
      annotations:
        nil: nil
      nodePort:

  root:
    enabled: true
    endpoint: root
    host: root
    service:
      type: ClusterIP
      annotations:
        nil: nil
      nodePort:

  consoleApi:
    enabled: true
    endpoint: console-server
    image: spaceone/console-api:latest
    service:
      type: ClusterIP
      annotations:
        nil: nil
      nodePort:


supervisor:
  enabled: true
  imagePullPolicy: IfNotPresent
  supervisor:
    endpoint: supervisor
    image: spaceone/supervisor:latest
    replicas: 1
    imagePullPolicy: IfNotPresent
    token: # yaml for TOKEN or TOKEN_INFO
      protocol: consul
      config:
        host: "{{ .Values.consul.host }}"
      uri: debug/supervisor/TOKEN
    plugin:
      imageRepository: pyengine
    service:
      type: ClusterIP
      annotations:
        nil: nil
      nodePort:
  kubectlProxy:
    image: spaceone/kubectl-proxy

#######
# Vault reference : https://www.vaultproject.io/docs/platform/k8s/helm/configuration
#######
#vault:
#  global:
#    enabled: true
#  server:
#    dev:
#      enabled: true
#  name: hello