{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: redis
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.redis.service.ports | indent 4 }}
  selector:
    helm.stargate.spaceone.dev/service: redis
  sessionAffinity: None
  type: {{ .Values.redis.service.type }}
{{- end }}