{{- if .Values.frontend.enabled }}
  {{- if .Values.frontend.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $value := .Values.frontend.console.service.annotations }}
      {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: console
  name: console
  namespace: {{ .Release.Namespace }}
spec:
    {{- range $key, $value := .Values.frontend.console.extraSpec }}
      {{- if not (eq $key "nil") }}
  {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
    {{- with .Values.frontend.console }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      {{- if and (or (eq .service.type "NodePort") (eq .service.type "LoadBalancer")) .service.nodePort }}
      nodePort: {{ .service.nodePort }}
      {{- end}}
  selector:
    helm.stargate.spaceone.dev/service: console
  sessionAffinity: None
  type: {{ .service.type }}
    {{- end }}
  {{- end }}
---
  {{- if .Values.frontend.root.enabled }}
# this service let you access to console through http://root by kubefwd
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $value := .Values.frontend.root.service.annotations }}
      {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: console
  name: root
  namespace: {{ .Release.Namespace }}
spec:
    {{- range $key, $value := .Values.frontend.root.extraSpec }}
      {{- if not (eq $key "nil") }}
  {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
    {{- with .Values.frontend.root }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      {{- if and (or (eq .service.type "NodePort") (eq .service.type "LoadBalancer")) .service.nodePort }}
      nodePort: {{ .service.nodePort }}
      {{- end}}
  selector:
    helm.stargate.spaceone.dev/service: console
  sessionAffinity: None
  type: {{ .service.type }}
    {{- end }}
  {{- end }}
{{- end }}