{{ if .Values.frontend.enabled }}
{{ if .Values.frontend.consoleApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: console-server
  name: console-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31760
  selector:
    helm.stargate.spaceone.dev/service: console-server
  sessionAffinity: None
  type: NodePort
{{ end }}
{{ end }}