{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.inventoryWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: inventory-worker
  name: inventory-worker
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: 30059
      port: 50051
      protocol: TCP
  selector:
    helm.stargate.spaceone.dev/service: inventory-worker
  sessionAffinity: None
  type: NodePort
{{ end }}
{{ end }}